const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const test = require('node:test');
const vm = require('node:vm');
const { expand } = require('./_load');
const root = path.resolve(__dirname, '..');
const ctx = vm.createContext({console, Math, JSON, Date, Image: class {}, setTimeout:()=>1, clearTimeout:()=>{}, performance:{now:()=>0}});
ctx.window=ctx;
for(const file of expand(['characters','ai','combat','adventure_content']).concat(['adventure/js/map/map.js','adventure/js/deck/adventure_deck.js','adventure/js/engine/adventure_engine.js','adventure/js/engine/shop.js','adventure/js/engine/rewards.js','adventure/js/engine/inventory.js','adventure/js/engine/combat_result.js','adventure/js/battle/battle_engine.js','adventure/js/battle/adventure_battle_items.js']))vm.runInContext(fs.readFileSync(path.join(root,file),'utf8'),ctx,{filename:file});
const card=()=>({value:2,color:'RED',isNumberCard:true});
function classic(){const e=new ctx.Engine();e.start('Ryan','Saiki');e.later=()=>{};return e;}
function adventure(two=false,testMode=false){const e=new ctx.AdventureBattleEngine();e.later=()=>{};const config={player:'Ryan',opponent:'CastleEagle',opponent1:'CastleWolf',opponent2:'CastleWolf',testMode,playerPile:{deck:Array.from({length:12},card),hand:Array.from({length:5},card),discard:[],handLimit:5}};if(two)e.startAdventure1v2(config);else e.startAdventure(config);return e;}
test('quicksand caps at one, remains persistent, and does not duplicate feedback',()=>{const e=classic();e.quicksand(e.s.player);e.quicksand(e.s.player,8);assert.equal(e.s.player.quicksand,1);assert.equal(e.getHandLimit('player'),4);assert.equal(e.s.handLimit,5);assert.equal(e.events.filter(x=>x.kind==='quicksand').length,1);e.settleBurn(e.s.player);assert.equal(e.s.player.quicksand,1);});
test('quicksand uses the effective limit for player discard, AI trim, and refill',()=>{const e=classic();e.quicksand(e.s.player);e.quicksand(e.s.ai);e.endTurn();assert.equal(e.s.phase,'PLAYER_DISCARD');e.s.selectedCards=[0];e.confirmDiscard();assert.equal(e.s.forcedDiscard,false);assert.equal(e.h.player.length,4);e.trimAI();assert.equal(e.h.ai.length,4);e.h.player=[];e.h.ai=[];e.fillHands(false);assert.equal(e.h.player.length,4);assert.equal(e.h.ai.length,4);});
test('ordinary and full cleanses restore the base limit without drawing',()=>{const e=classic();e.quicksand(e.s.player);const size=e.h.player.length;e.clean(e.s.player,false,'quicksand');assert.equal(e.getHandLimit('player'),5);assert.equal(e.h.player.length,size);e.quicksand(e.s.player);e.clean(e.s.player,true);assert.equal(e.s.player.quicksand,0);e.quicksand(e.s.player);e.clearDebuffs(e.s.player);assert.equal(e.getHandLimit('player'),5);});
test('1v2 limits are per participant and preserve survivor rule',()=>{const e=classic();e.start1v2('Ryan','Saiki','Leon');e.quicksand(e.s.player);e.quicksand(e.s.ai2);assert.equal(e.getHandLimit('player'),9);assert.equal(e.getHandLimit('ai'),5);assert.equal(e.getHandLimit('ai2'),4);e.s.ai.alive=false;assert.equal(e.getHandLimit('ai2'),9);e.h.ai2=[];e.fillAIHands1v2();assert.equal(e.h.ai2.length,9);});
test('adventure/test trophies target NPC2, leave base piles unchanged and bridge-draw',()=>{for(const testMode of [false,true]){const e=adventure(true,testMode);e.s.attackTarget='ai2';const n=e.h.player.length;e.useTrophyWhite(ctx.AdventureDeck.trophyWhite('QuicksandTrophy'),e.s.ai2);assert.equal(e.s.ai2.quicksand,1);assert.equal(e.s.ai.quicksand||0,0);assert.equal(e.s.player.quicksand||0,0);assert.equal(e.getHandLimit('ai2'),1);assert.equal(e.piles.ai2.handLimit,2);assert.equal(e.h.player.length,n+1);e.h.ai2.splice(0);e.fillHands1v2(false);assert.equal(e.h.ai2.length,1);}});
test('boss and accessory limits derive from metadata without double subtraction',()=>{const e=adventure();e.quicksand(e.s.ai);assert.equal(e.getHandLimit('ai'),2);e.piles.player.handLimit=6;e.quicksand(e.s.player);assert.equal(e.getHandLimit('player'),5);assert.equal(e.getHandLimit('player'),5);ctx.StatusService.clearAll(e.s.player);assert.equal(e.getHandLimit('player'),6);});
test('combat snapshots retain quicksand and its reduced limit',()=>{const e=classic();e.quicksand(e.s.player);const save=e.combatSnapshot();const restored=new ctx.Engine();restored.restoreCombatSnapshot(save);assert.equal(restored.getHandLimit('player'),4);assert.equal(restored.s.handLimit,5);});
test('forge requires and consumes one explicit universal core, plus origin or substitute',()=>{const def=ctx.AdventureRegistry.getItem('QuicksandTrophy');assert.deepEqual(Array.from(def.beastTradeCost),['ben','wuneng']);const c=new ctx.AdventureCurrency();c.tokens.ben=2;assert.equal(c.canPayBeastCost(def.beastTradeCost),false);c.tokens.wuneng=1;assert.equal(c.payBeastCost(def.beastTradeCost),true);assert.equal(c.tokens.ben,1);assert.equal(c.tokens.wuneng,0);c.tokens.ben=0;c.tokens.wuneng=1;assert.equal(c.canPayBeastCost(def.beastTradeCost),false);c.tokens.wuneng=2;assert.equal(c.payBeastCost(def.beastTradeCost),true);assert.equal(c.tokens.wuneng,0);});
test('playable highlight never whitens or pulses the card face',()=>{const css=fs.readFileSync(path.join(root,'css/game.css'),'utf8');const base=css.match(/\.card-canvas\.card-playable \{([^}]+)\}/)[1];assert.match(base,/animation: none/);assert.match(base,/filter: none/);assert.doesNotMatch(base,/inset/);assert.doesNotMatch(css,/@keyframes cardPlayablePulse/);assert.ok(fs.existsSync(path.join(root,'icons/buff_icons/sandblind.webp')));});
